### ISSUE TITLE
Starting

### ISSUE THREAD

**Issue by Arafeus** [Nadromar/TrinityCreator#17]
Hello, i started Trinity Creator once, after first instalation, but when i closed program, i can to open it again, even reinstal or repair dont work.

**Comment by Nadromar** [comment]
I'm not sure what went wrong but you can try clearing the config.
Press WIN+R on your keyboard and enter %appdata%\..\Local\RStijn
Then delete folders with TrinityCreator in the name.
This should clear your settings & make the program work again.
