### ISSUE TITLE
Crashes on launch

### ISSUE THREAD

**Issue by aequasi** [Nadromar/TrinityCreator#18]
Something about System.Windows.Markup.XamlParse

**Comment by Nadromar** [comment]
Hello,

Please ensure your PC is Windows 7 or newer have the prerequisites installed:
https://www.microsoft.com/en-us/download/details.aspx?id=30653

If this fails, press Ctrl+R and enter "%USERPROFILE%\AppData\Local\" and delete a folder called "Nadromar" to reset any faulty settings.
