### ISSUE TITLE
Unable to connect to any of the specified MySQL hosts.

### ISSUE THREAD

**Issue by NovakZ** [Nadromar/TrinityCreator#19]
So I'm trying to connect the Trinity Creator to my wotlk database but it doesn't work. When I try to connect with the user Trinity which belongs to the WOD client it works but when I try with another user which uses another myslq service it doesn't work.

**Comment by Nadromar** [comment]
Is there an error message?

**Comment by NovakZ** [comment]
Nope, just the message:
![123](https://cloud.githubusercontent.com/assets/26920616/24812475/0e5614a4-1b7f-11e7-88fd-48d9df8fb2fa.png)

I have my MYSQL service for WOTLK client started and the port I use is 3307 instead of 3306, because I use  3306 for WOD client so the databases of both clients do not mess up.

**Comment by Nadromar** [comment]
I've just released a new version where you can choose the MySQL port number.
Restart the program to get an update. Haven't tested it though, so let me know if it works.

**Comment by NovakZ** [comment]
![1233](https://cloud.githubusercontent.com/assets/26920616/24813191/fa09b282-1b81-11e7-82ac-485a7b71257b.png)
Thanks Nadromar! You're a lifesaver! Cannot thank you enough for the job you've done!

**Comment by Nadromar** [comment]
Happy to help. ^^
