### ISSUE TITLE
Bug on item creation

### ISSUE THREAD

**Issue by Telepathique** [Nadromar/TrinityCreator#21]
Hi on all of the items that i create for my server i always have a meta gem slot please could you correct your template for 

socketColor1 from 1 to 0 :)

Thanks.

Telepathique

**Comment by Nadromar** [comment]
Thanks for reporting.
I'm aware that socketColor1 is set to one, however, as long as the socket count remains 0, this is not an issue.
This can be fixed but it seems like pointless effort for a non-issue.

However, it it does somehow show up on the item in-game, please do let me know and I'll get on it.

**Comment by Nadromar** [comment]
Fixed in ce7260675a958c9ef598cda6f0a3d8c101a9b5f5
