### ISSUE TITLE
Nostalrius Core support

### ISSUE THREAD

**Issue by gore23** [Nadromar/TrinityCreator#22]
I use a 1.12.1 nostalrious based vanilla version of wow. This does not seem to work for me, but the main reasons seems to be a single error about sockets. Could you add a Vanilla check mark option that makes it only support what vanilla supported, you know like remove the sockets for example. I do not know if there is anything else that would need changed for that, but that is the only error I had. =/

**Comment by gore23** [comment]
I did some testing, it seems that the following are the problems encountered when imported into my 1.12.1 server. BUT, after they are removed the item works perfectly well afterwards. Really awesome work on this, your great. Just plz make that option that gets rid of these for 1.12.1 users.

socketBonus
socketColor_1
socketContent_1
FlagsExtra
StatsCount

**Comment by Nadromar** [comment]
You can change the emulator from Trinity 335a to nostalrius / mangos under in the top menu under Settings > Select Emulator > cMangos.
Feel free to re-open the ticket if it for some reason still doesn't work after that.

**Comment by gore23** [comment]
It seems to be working with the few times that I tried it, but it seems dangerous. I want to make some really cool items, but it is soo difficult and time consuming with how it is now to even figure out. The thing is, the vanilla seems to use aura's instead for things like crit and percentages and junk that is added to the weapons. So it bugs out if you try using those options and just spams mana repeatedly for some of the stats. If you just use the bare bones stats like strength, health, block, and jazz it is fine though. 

If you were able to set it up so that it removes those non existent yet stats, and make a selection for aura adding. That would be a absolute lifesaver for that option. at least for some of the most common and fun ones. Or some of the unique and cool ones for big weapons like sulfuras and thunderfury so that we can get some cool moded weapons that have them. be really neat and extremely appreciated. Best application out there from what I have seen for this type of stuff. Dont even have that website anymore T.T

**Comment by Nadromar** [comment]
Thanks for the update. I'll keep the ticket open to make sure this happens.
The website you're referring to is probably wow-v.com, though it seems to have shut down recently. :/

**Comment by Nadromar** [comment]
Added to #49

**Comment by NotCoffee418** [comment]
Light's Hope emulator is now supported.
