### ISSUE TITLE
No Cloak Option

### ISSUE THREAD

**Issue by Hjodir** [Nadromar/TrinityCreator#23]
Hi, I just wanted to say that your item creator does not include the ability to create a cloak. This should be located under Armor > Cloth > Back, but there is no Back slot. This isn't even present in miscellaneous, either. As it stands, cloaks will have to be created manually in the database or with another program.

**Comment by Hjodir** [comment]
Update: As it turns out, this item creator really just doesn't work at all. The added items may show up in the database when exported, but they're just not showing-up in game. 

Furthermore, the first few items I tried creating in this program are shown as being present in the database, but in the game, the Entry IDs are connected to items I duplicated and later removed from the database before I ever touched this program, but wouldn't show up-in game until I started playing with this program. 

Now, whatever's going on here, I have no idea because there is no logical reason why items deleted from the database are now showing up in the game instead of the ones that were created with this program. 

Even ignoring that big problem, the bigger problem is that independent items created with this program simply do not show up in the game.

**Comment by Nadromar** [comment]
I believe cloaks are under misc > back.
Are you sure you restarted trinity core before trying to add the item?
When you overtide an ID that already existes, it can cause some weire stuff to happen. Do shut down your wow client & clear your cache if you intend to do that. Which yoi probably shouldnt.

**Comment by Nadromar** [comment]
There was indeed no cloak option.
Fixed in 6f27cac1d1a4aa52beb03bb9a5448c408618e025  (untested)
Please create a new ticket if you have any other issues.
