### ISSUE TITLE
Please make compatible with Azerothcore 3.3.5

### ISSUE THREAD

**Issue by Mowhok** [Nadromar/TrinityCreator#24]

**Comment by Nadromar** [comment]
Thanks for the suggestion.
It's quite a bit of work to add support for a new emulator so I'll wait until more people request it.
If anyone else wants this, let me know below.

**Comment by Mowhok** [comment]
azerothcore is trinity basically but a few changes

**Comment by Nadromar** [comment]
New version (1988d6de3fa622c28daec7b3e321db38a3719f67) supports items quests & creature for AzerothCore.
Haven't tested it yet though so let me know if something doesn't work.

Problem is, while the changes are small, this program isn't equipped to add easy compatibility for other emulators so the code is dirty. It'll have to do for now though.

**Comment by BarbzYHOOL** [comment]
>Just an FYI but trinitycore will make your life easier if you're gonna be adding custom stuff.

Not really. Ty for these changes though
