### ISSUE TITLE
Loading on Windows 10

### ISSUE THREAD

**Issue by Astron-One** [Nadromar/TrinityCreator#27]
Hi, I am unable to get this to load in Windows 10, I click to open, and the program simply does nothing.
Hoping there is a simple fix, haven't found anything from a search.

**Comment by Nadromar** [comment]
Try checking if there's a process TrinityCreator running. If there is, kill the process & try again.
Apparently that happens in some situations while updating.
Otherwise, there's no reason it shouldn't work on windows 10.

**Comment by Astron-One** [comment]
Thanks. No process running for it.
Trying to figure out how to read error log, it does record something when I go to open it, but no determination as to what.
This is a clean install bar from the Trinity server a Wow instance and your creator.

**Comment by Nadromar** [comment]
You installed it through the installer, right? You didn't just download the exe and try to run it from there?

Mhhm, try to run it as admin maybe. There's currently no error logs, though Event Viewer might show the error. (right-click start button > event viewer)

Be sure to have .NET 4.5 installed, though I think it's installed natively in Windows 10.

You can also try to delete the settings files. I doubt it'll help in this situation but it's worth a shot.
Press Win+R > type in: %appdata%\..\Local\Nadromar > if it opens, delete any folder(s) with TrinityCreator in the name.

If none of that helps i'll add some basic error logging for situations like that.

**Comment by Nadromar** [comment]
Scratch that last message. Apparently a component of this program doesn't cross-compile.
Fixed in ec941724c20155766cdead0d64133be30cec9c0d
Download the new version: https://github.com/Nadromar/TrinityCreator/blob/master/TrinityCreatorSetup/bin/Release/TrinityCreatorSetup.msi?raw=true
