### ISSUE TITLE
Program Crashing Immediately After Being Opened

### ISSUE THREAD

**Issue by Ve-Vardmadr** [Nadromar/TrinityCreator#28]
Problem signature:
  Problem Event Name:	CLR20r3
  Problem Signature 01:	TrinityCreator.exe
  Problem Signature 02:	1.0.7.28
  Problem Signature 03:	59f1321e
  Problem Signature 04:	TrinityCreator
  Problem Signature 05:	1.0.7.28
  Problem Signature 06:	59f1321e
  Problem Signature 07:	d8
  Problem Signature 08:	c
  Problem Signature 09:	System.Windows.Markup.XamlParse
  OS Version:	6.1.7600.2.0.0.256.48
  Locale ID:	1033
  Additional Information 1:	0a9e
  Additional Information 2:	0a9e372d3b4ad19135b953a78882e789
  Additional Information 3:	0a9e
  Additional Information 4:	0a9e372d3b4ad19135b953a78882e789

On Win7 32bit

**Comment by Nadromar** [comment]
Download the new version:
https://github.com/Nadromar/TrinityCreator/blob/master/TrinityCreatorSetup/bin/Release/TrinityCreatorSetup.msi?raw=true

If that doesn't fix it, please let me know.
