### ISSUE TITLE
Request: 2.4.3 support

### ISSUE THREAD

**Issue by Mowhok** [Nadromar/TrinityCreator#31]
Hello Dude i appreciate your work and owuld like to ask if oyu have planned on adding more 2.4.3 options ? TC, Oregon for example ?

best regards

**Comment by Nadromar** [comment]
I'll keep the issue open. If anyone else would also like to see TBC support, put a comment below and I might add it.

TBC can be added much easier than legion support so it could happen if there's enough demand.

**Comment by Mowhok** [comment]
Okay nice to hear that !
So OregonCore would be nice if you could add stuff with TCreator

**Comment by Nadromar** [comment]
Added to #49
