### ISSUE TITLE
Still crashes on start up,

### ISSUE THREAD

**Issue by Astron-One** [Nadromar/TrinityCreator#33]
Changed to Win 7 32 bit for server. Still have issue where program will crash as soon as it's run.

> `<?xml version="1.0" encoding="UTF-16"?>
> <DATABASE>
> <EXE NAME="TrinityCreator.exe" FILTER="CMI_FILTER_PRIVACY">
>     <MATCHING_FILE NAME="CefSharp.BrowserSubprocess.Core.dll" SIZE="688640" CHECKSUM="0xCE5D631" MODULE_TYPE="WIN32" PE_CHECKSUM="0xB12F0" LINKER_VERSION="0x0" LINK_DATE="05/03/2016 10:29:58" UPTO_LINK_DATE="05/03/2016 10:29:58" EXPORT_NAME="CefSharp.BrowserSubprocess.Core.dll" EXE_WRAPPER="0x0" />
>     <MATCHING_FILE NAME="CefSharp.BrowserSubprocess.exe" SIZE="10752" CHECKSUM="0x6BE21CAA" BIN_FILE_VERSION="49.0.0.0" BIN_PRODUCT_VERSION="49.0.0.0" PRODUCT_VERSION="49.0.0.0" FILE_DESCRIPTION="CefSharp.BrowserSubprocess" COMPANY_NAME="The CefSharp Authors" PRODUCT_NAME="CefSharp" FILE_VERSION="49.0.0.0" ORIGINAL_FILENAME="CefSharp.BrowserSubprocess.exe" INTERNAL_NAME="CefSharp.BrowserSubprocess.exe" LEGAL_COPYRIGHT="Copyright © The CefSharp Authors 2010-2016" VERDATEHI="0x0" VERDATELO="0x0" VERFILEOS="0x4" VERFILETYPE="0x1" MODULE_TYPE="WIN32" PE_CHECKSUM="0xD1AD" LINKER_VERSION="0x0" UPTO_BIN_FILE_VERSION="49.0.0.0" UPTO_BIN_PRODUCT_VERSION="49.0.0.0" LINK_DATE="05/03/2016 10:30:01" UPTO_LINK_DATE="05/03/2016 10:30:01" VER_LANGUAGE="Language Neutral [0x0]" EXE_WRAPPER="0x0" />
>     <MATCHING_FILE NAME="CefSharp.Core.dll" SIZE="1028608" CHECKSUM="0x839A353" MODULE_TYPE="WIN32" PE_CHECKSUM="0xFBC96" LINKER_VERSION="0x0" LINK_DATE="05/03/2016 10:29:44" UPTO_LINK_DATE="05/03/2016 10:29:44" EXPORT_NAME="CefSharp.Core.dll" EXE_WRAPPER="0x0" />
>     <MATCHING_FILE NAME="CefSharp.dll" SIZE="157696" CHECKSUM="0xF6FECDCD" BIN_FILE_VERSION="49.0.0.0" BIN_PRODUCT_VERSION="49.0.0.0" PRODUCT_VERSION="49.0.0.0" FILE_DESCRIPTION="CefSharp" COMPANY_NAME="The CefSharp Authors" PRODUCT_NAME="CefSharp" FILE_VERSION="49.0.0.0" ORIGINAL_FILENAME="CefSharp.dll" INTERNAL_NAME="CefSharp.dll" LEGAL_COPYRIGHT="Copyright © The CefSharp Authors 2010-2016" VERDATEHI="0x0" VERDATELO="0x0" VERFILEOS="0x4" VERFILETYPE="0x2" MODULE_TYPE="WIN32" PE_CHECKSUM="0x2F338" LINKER_VERSION="0x0" UPTO_BIN_FILE_VERSION="49.0.0.0" UPTO_BIN_PRODUCT_VERSION="49.0.0.0" LINK_DATE="05/03/2016 10:29:24" UPTO_LINK_DATE="05/03/2016 10:29:24" VER_LANGUAGE="Language Neutral [0x0]" EXE_WRAPPER="0x0" />
>     <MATCHING_FILE NAME="CefSharp.WinForms.dll" SIZE="22528" CHECKSUM="0xC0B64690" BIN_FILE_VERSION="49.0.0.0" BIN_PRODUCT_VERSION="49.0.0.0" PRODUCT_VERSION="49.0.0.0" FILE_DESCRIPTION="CefSharp.WinForm" COMPANY_NAME="The CefSharp Authors" PRODUCT_NAME="CefSharp" FILE_VERSION="49.0.0.0" ORIGINAL_FILENAME="CefSharp.WinForms.dll" INTERNAL_NAME="CefSharp.WinForms.dll" LEGAL_COPYRIGHT="Copyright © The CefSharp Authors 2010-2016" VERDATEHI="0x0" VERDATELO="0x0" VERFILEOS="0x4" VERFILETYPE="0x2" MODULE_TYPE="WIN32" PE_CHECKSUM="0x8F39" LINKER_VERSION="0x0" UPTO_BIN_FILE_VERSION="49.0.0.0" UPTO_BIN_PRODUCT_VERSION="49.0.0.0" LINK_DATE="05/03/2016 10:29:49" UPTO_LINK_DATE="05/03/2016 10:29:49" VER_LANGUAGE="Language Neutral [0x0]" EXE_WRAPPER="0x0" />
>     <MATCHING_FILE NAME="d3dcompiler_43.dll" SIZE="2106216" CHECKSUM="0x6016217E" BIN_FILE_VERSION="9.29.952.3111" BIN_PRODUCT_VERSION="9.29.952.3111" PRODUCT_VERSION="9.29.952.3111" FILE_DESCRIPTION="Direct3D HLSL Compiler" COMPANY_NAME="Microsoft Corporation" PRODUCT_NAME="Microsoft® DirectX for Windows®" FILE_VERSION="9.29.952.3111" ORIGINAL_FILENAME="d3dcompiler_43.dll" INTERNAL_NAME="d3dcompiler_43.dll" LEGAL_COPYRIGHT="Copyright © Microsoft Corp. 1994-2007" VERDATEHI="0x0" VERDATELO="0x0" VERFILEOS="0x10001" VERFILETYPE="0x2" MODULE_TYPE="WIN32" PE_CHECKSUM="0x20A54F" LINKER_VERSION="0x60001" UPTO_BIN_FILE_VERSION="9.29.952.3111" UPTO_BIN_PRODUCT_VERSION="9.29.952.3111" LINK_DATE="05/22/2010 01:24:09" UPTO_LINK_DATE="05/22/2010 01:24:09" EXPORT_NAME="D3DCOMPILER_43.dll" VER_LANGUAGE="English (United States) [0x409]" EXE_WRAPPER="0x0" />
>     <MATCHING_FILE NAME="d3dcompiler_47.dll" SIZE="3709120" CHECKSUM="0x21CA7E38" BIN_FILE_VERSION="10.0.10586.15" BIN_PRODUCT_VERSION="10.0.10586.15" PRODUCT_VERSION="10.0.10586.15" FILE_DESCRIPTION="Direct3D HLSL Compiler for Redistribution" COMPANY_NAME="Microsoft Corporation" PRODUCT_NAME="Microsoft® Windows® Operating System" FILE_VERSION="10.0.10586.15 (th2_release.151119-1817)" ORIGINAL_FILENAME="d3dcompiler_47.dll" INTERNAL_NAME="d3dcompiler_47.dll" LEGAL_COPYRIGHT="© Microsoft Corporation. All rights reserved." VERDATEHI="0x0" VERDATELO="0x0" VERFILEOS="0x40004" VERFILETYPE="0x2" MODULE_TYPE="WIN32" PE_CHECKSUM="0x38D718" LINKER_VERSION="0xA0000" UPTO_BIN_FILE_VERSION="10.0.10586.15" UPTO_BIN_PRODUCT_VERSION="10.0.10586.15" LINK_DATE="11/20/2015 04:53:44" UPTO_LINK_DATE="11/20/2015 04:53:44" EXPORT_NAME="D3DCOMPILER_47.dll" VER_LANGUAGE="English (United States) [0x409]" EXE_WRAPPER="0x0" />
>     <MATCHING_FILE NAME="libcef.dll" SIZE="48936448" CHECKSUM="0xD5BF866" BIN_FILE_VERSION="3.2623.1396.0" BIN_PRODUCT_VERSION="3.2623.1396.0" PRODUCT_VERSION="3.2623.1396.g0451528" FILE_DESCRIPTION="Chromium Embedded Framework (CEF) Dynamic Link Library" PRODUCT_NAME="Chromium Embedded Framework (CEF) Dynamic Link Library" FILE_VERSION="3.2623.1396.g0451528" ORIGINAL_FILENAME="libcef.dll" INTERNAL_NAME="libcef" LEGAL_COPYRIGHT="Copyright (C) 2016 The Chromium Embedded Framework Authors" VERDATEHI="0x0" VERDATELO="0x0" VERFILEOS="0x4" VERFILETYPE="0x2" MODULE_TYPE="WIN32" PE_CHECKSUM="0x0" LINKER_VERSION="0x0" UPTO_BIN_FILE_VERSION="3.2623.1396.0" UPTO_BIN_PRODUCT_VERSION="3.2623.1396.0" LINK_DATE="03/31/2016 06:43:37" UPTO_LINK_DATE="03/31/2016 06:43:37" EXPORT_NAME="libcef.dll" VER_LANGUAGE="English (United States) [0x409]" EXE_WRAPPER="0x0" />
>     <MATCHING_FILE NAME="libEGL.dll" SIZE="75264" CHECKSUM="0x82E75F5A" BIN_FILE_VERSION="2.1.0.0" BIN_PRODUCT_VERSION="2.1.0.0" PRODUCT_VERSION="2.1.0.4e9536d0f612" FILE_DESCRIPTION="ANGLE libEGL Dynamic Link Library" PRODUCT_NAME="ANGLE libEGL Dynamic Link Library" FILE_VERSION="2.1.0.4e9536d0f612" ORIGINAL_FILENAME="libEGL.dll" INTERNAL_NAME="libEGL" LEGAL_COPYRIGHT="Copyright (C) 2015 Google Inc." VERDATEHI="0x0" VERDATELO="0x0" VERFILEOS="0x4" VERFILETYPE="0x2" MODULE_TYPE="WIN32" PE_CHECKSUM="0x0" LINKER_VERSION="0x0" UPTO_BIN_FILE_VERSION="2.1.0.0" UPTO_BIN_PRODUCT_VERSION="2.1.0.0" LINK_DATE="03/30/2016 22:34:28" UPTO_LINK_DATE="03/30/2016 22:34:28" EXPORT_NAME="libEGL.dll" VER_LANGUAGE="English (United States) [0x409]" EXE_WRAPPER="0x0" />
>     <MATCHING_FILE NAME="libGLESv2.dll" SIZE="1665024" CHECKSUM="0x30C09CF3" BIN_FILE_VERSION="2.1.0.0" BIN_PRODUCT_VERSION="2.1.0.0" PRODUCT_VERSION="2.1.0.4e9536d0f612" FILE_DESCRIPTION="ANGLE libGLESv2 Dynamic Link Library" PRODUCT_NAME="ANGLE libGLESv2 Dynamic Link Library" FILE_VERSION="2.1.0.4e9536d0f612" ORIGINAL_FILENAME="libGLESv2.dll" INTERNAL_NAME="libGLESv2" LEGAL_COPYRIGHT="Copyright (C) 2015 Google Inc." VERDATEHI="0x0" VERDATELO="0x0" VERFILEOS="0x4" VERFILETYPE="0x2" MODULE_TYPE="WIN32" PE_CHECKSUM="0x0" LINKER_VERSION="0x0" UPTO_BIN_FILE_VERSION="2.1.0.0" UPTO_BIN_PRODUCT_VERSION="2.1.0.0" LINK_DATE="03/30/2016 22:34:22" UPTO_LINK_DATE="03/30/2016 22:34:22" EXPORT_NAME="libGLESv2.dll" VER_LANGUAGE="English (United States) [0x409]" EXE_WRAPPER="0x0" />
>     <MATCHING_FILE NAME="MySql.Data.dll" SIZE="457728" CHECKSUM="0x20C368A" BIN_FILE_VERSION="6.9.8.0" BIN_PRODUCT_VERSION="6.9.8.0" PRODUCT_VERSION="6.9.8" FILE_DESCRIPTION="MySql.Data.dll" COMPANY_NAME="Oracle" FILE_VERSION="6.9.8.0" ORIGINAL_FILENAME="MySql.Data.dll" INTERNAL_NAME="MySql.Data.dll" LEGAL_COPYRIGHT="Copyright © 2004, 2015, Oracle and/or its affiliates. All rights reserved." VERDATEHI="0x0" VERDATELO="0x0" VERFILEOS="0x4" VERFILETYPE="0x2" MODULE_TYPE="WIN32" PE_CHECKSUM="0x72EA4" LINKER_VERSION="0x0" UPTO_BIN_FILE_VERSION="6.9.8.0" UPTO_BIN_PRODUCT_VERSION="6.9.8.0" LINK_DATE="10/02/2015 15:05:25" UPTO_LINK_DATE="10/02/2015 15:05:25" VER_LANGUAGE="Language Neutral [0x0]" EXE_WRAPPER="0x0" />
>     <MATCHING_FILE NAME="TrinityCreator.exe" SIZE="1771008" CHECKSUM="0xC94BA5ED" BIN_FILE_VERSION="1.0.7.29" BIN_PRODUCT_VERSION="1.0.7.29" PRODUCT_VERSION="1.0.7.29" FILE_DESCRIPTION="TrinityCreator" COMPANY_NAME="Nadromar" PRODUCT_NAME="TrinityCreator" FILE_VERSION="1.0.7.29" ORIGINAL_FILENAME="TrinityCreator.exe" INTERNAL_NAME="TrinityCreator.exe" LEGAL_COPYRIGHT="Copyright © Nadromar 2017" VERDATEHI="0x0" VERDATELO="0x0" VERFILEOS="0x4" VERFILETYPE="0x1" MODULE_TYPE="WIN32" PE_CHECKSUM="0x0" LINKER_VERSION="0x0" UPTO_BIN_FILE_VERSION="1.0.7.29" UPTO_BIN_PRODUCT_VERSION="1.0.7.29" LINK_DATE="11/12/2017 15:16:16" UPTO_LINK_DATE="11/12/2017 15:16:16" VER_LANGUAGE="Language Neutral [0x0]" EXE_WRAPPER="0x0" FILE_ID="00000716e886c61f66ea2b2b0419de5594b2a38d9247" PROGRAM_ID="0000da39a3ee5e6b4b0d3255bfef95601890afd80709" />
> </EXE>
> <EXE NAME="KERNELBASE.dll" FILTER="CMI_FILTER_THISFILEONLY">
>     <MATCHING_FILE NAME="KernelBase.dll" SIZE="294400" CHECKSUM="0x75D7DDA6" BIN_FILE_VERSION="6.1.7601.23889" BIN_PRODUCT_VERSION="6.1.7601.23889" PRODUCT_VERSION="6.1.7601.18015" FILE_DESCRIPTION="Windows NT BASE API Client DLL" COMPANY_NAME="Microsoft Corporation" PRODUCT_NAME="Microsoft® Windows® Operating System" FILE_VERSION="6.1.7601.18015 (win7sp1_gdr.121129-1432)" ORIGINAL_FILENAME="Kernelbase" INTERNAL_NAME="Kernelbase" LEGAL_COPYRIGHT="© Microsoft Corporation. All rights reserved." VERDATEHI="0x0" VERDATELO="0x0" VERFILEOS="0x40004" VERFILETYPE="0x2" MODULE_TYPE="WIN32" PE_CHECKSUM="0x48328" LINKER_VERSION="0x60001" UPTO_BIN_FILE_VERSION="6.1.7601.23889" UPTO_BIN_PRODUCT_VERSION="6.1.7601.23889" LINK_DATE="08/11/2017 06:22:22" UPTO_LINK_DATE="08/11/2017 06:22:22" EXPORT_NAME="KERNELBASE.dll" VER_LANGUAGE="English (United States) [0x409]" EXE_WRAPPER="0x0" />
> </EXE>
> <EXE NAME="kernel32.dll" FILTER="CMI_FILTER_THISFILEONLY">
>     <MATCHING_FILE NAME="kernel32.dll" SIZE="872448" CHECKSUM="0x3A0A495D" BIN_FILE_VERSION="6.1.7601.23889" BIN_PRODUCT_VERSION="6.1.7601.23889" PRODUCT_VERSION="6.1.7601.18015" FILE_DESCRIPTION="Windows NT BASE API Client DLL" COMPANY_NAME="Microsoft Corporation" PRODUCT_NAME="Microsoft® Windows® Operating System" FILE_VERSION="6.1.7601.18015 (win7sp1_gdr.121129-1432)" ORIGINAL_FILENAME="kernel32" INTERNAL_NAME="kernel32" LEGAL_COPYRIGHT="© Microsoft Corporation. All rights reserved." VERDATEHI="0x0" VERDATELO="0x0" VERFILEOS="0x40004" VERFILETYPE="0x2" MODULE_TYPE="WIN32" PE_CHECKSUM="0xE1F61" LINKER_VERSION="0x60001" UPTO_BIN_FILE_VERSION="6.1.7601.23889" UPTO_BIN_PRODUCT_VERSION="6.1.7601.23889" LINK_DATE="08/11/2017 06:22:21" UPTO_LINK_DATE="08/11/2017 06:22:21" EXPORT_NAME="KERNEL32.dll" VER_LANGUAGE="English (United States) [0x409]" EXE_WRAPPER="0x0" />
> </EXE>
> </DATABASE>
> 
> > `

**Comment by Nadromar** [comment]
Try installing this, and please let me know wether or not it works:
https://www.microsoft.com/en-us/download/details.aspx?id=30679

Unfortunately it's the least useful component of the program causing these problems, the Model Viewer browser.

**Comment by Astron-One** [comment]
sadly still no joy.
no idea whats so different about my installs.
this like before was a clean install of win 7 32 bit with only a folder of wow and the private server.

**Comment by Nadromar** [comment]
Alright, this version should almost certainly work.
https://github.com/Nadromar/TrinityCreator/blob/no-modelviewer/TrinityCreatorSetup/bin/Release/TrinityCreatorSetup.msi

Problem is that, while the program was initially compatible with Windows 7, it's not anymore due to the browser used for the Model Viewer which I have very little control over.
The alternate version above removes this model viewer and should resolve the issue.

It's kind of a lazy fix but, the model viewer is mostly a cosmetic component and it shouldn't interfere with compatibility.

Leme know if it works, thanks!

**Comment by Astron-One** [comment]
Very very happy right now.
Many thanks.

So, is it Win10 32bit I would need for the 'standard release' version?
Tried Win10 64 with no joy either.
This version works, so am happy anyway. :)
