### ISSUE TITLE
Form does not fully clear when using "Create new item" button

### ISSUE THREAD

**Issue by thelostsinner123** [Nadromar/TrinityCreator#34]
![image](https://user-images.githubusercontent.com/34170922/33499767-8a58d5e4-d693-11e7-9f4c-736debdb9a75.png)

As you can see, item preview does not change when a new item is created, and this raises a question as to whether or not the exporter .SQL file will be intact. Item rarity seems to update properly, however.

**Comment by Nadromar** [comment]
Thanks for the report.
Fixed in a6e825d77e0eff42d132b74b5e5dbfe9020aaa23
This only affected the preview, not the exported item itself.
