### ISSUE TITLE
How to get the program to connect to the database from another pc

### ISSUE THREAD

**Issue by sout12** [Nadromar/TrinityCreator#36]
How do i allow another PC to connect to the database ?

**Comment by Nadromar** [comment]
If it's in your local network you just gotta open your firewall & set the host to the local IP of your computer. You can google how to find that.
If you want access from outside your network, that's probably trickier, you'll probably have to set up port forwarding in your router.

This isn't really a trinitycreator issue so I'd recommend you google how to do all this.
Alternatively, you can export to SQL and import it to the database manually.
