### ISSUE TITLE
cMangos Creatures NIY

### ISSUE THREAD

**Issue by steamedham** [Nadromar/TrinityCreator#41]
no matter what i do, when i try to create a creature or loot table i can't because of this

**Comment by Nadromar** [comment]
Seems I haven't implemented it yet for cMangos. Sorry about that.
https://github.com/Nadromar/TrinityCreator/search?q=NotImplementedException&unscoped_q=NotImplementedException

**Comment by steamedham** [comment]
Did you fix it?

**Comment by Mowhok** [comment]
doesnt seem so

**Comment by Nadromar** [comment]
Yeah I skipped it because stats work differently from other emus.
I'm on it now.

**Comment by Nadromar** [comment]
Added in b088f7d41d5b2baefa87fc342ab8e393f0363489
