### ISSUE TITLE
Recent update

### ISSUE THREAD

**Issue by IllInuz** [Nadromar/TrinityCreator#48]
I just reinstalled the program, due to the fact it mentioned it had an update, however when running the installer it asked me to reboot my pc,.

I did, and reinstalled the program using the new downloaded installer.
Guess what? it didn't update, its still the old version i had before.

Everytime i attempt to launch the program now, its going to be asking for the update, which it for some reason can't fetch and says "Can't update automatically, please manually update"

Kindly look in to this.

**Comment by Nadromar** [comment]
I'm all over it. I bumped the version expecting to have a new release ready, didn't happen.
I'm on a spree here so, got any bugs that need fixing for a particular emulator before I release it?

**Comment by Nadromar** [comment]
Fixed in 7728492fb859196df502fd8004a02568fa293a58
