### ISSUE TITLE
LATEST TC Creature bug

### ISSUE THREAD

**Issue by Lucascn21** [Nadromar/TrinityCreator#54]
when trying to insert creature into creature_template, the query generated attempts to use the following columns resistanceHoly, resistanceFire, resistanceNature, resistanceFrost, resistanceShadow, resistanceArcane instead of resistance1, resistance2, etc.

I've selected the right emulator.

**Comment by Nadromar** [comment]
Yeah I blindly merged something that apparently affected it.
I'll push a build in a few hours with a bunch of fixes. If you want the working exe fast, leme know and i'll post it here already.

**Comment by Lucascn21** [comment]
yes please, that would be great.

**Comment by Nadromar** [comment]
[TrinityCreator.zip](https://github.com/Nadromar/TrinityCreator/files/2847446/TrinityCreator.zip)
Copypaste into your install folder, override the old one. If you find anything else leme know, updating all emulators and trying to decypher my garbage code atm so :P

**Comment by Lucascn21** [comment]
Thank you very much.

**Comment by Nadromar** [comment]
Fixed in 6e27ae3f8de97f61803ea23cf22868b356ccab26
I was gonna fix more issues (mainly the updater) but brain is fried so, maybe later.
Make sure to select your emulator again the ID may have changed.
