### ISSUE TITLE
TrinityCreator hello there is a problem!

### ISSUE THREAD

**Issue by AlexTremere** [Nadromar/TrinityCreator#60]
so after i made a vendor and put items in to him, a lot of items!!! :(
it did not save it. only some of them. 
every time i am exiting the program is says 
"that files my not be saved"
 how to save it there is no save tab of something like that.
and the funny thing is that the items and vendor are in the DB.

**Comment by Nadromar** [comment]
The message when you close the window always appears. It's just to make sure you don't accidentally click it off while you still have unsaved (not exported) changes.
Even if you did export, it will still appear.

As for the vendor.. All the application does is put the values into the database.
If they're there, it's an emulator / WoW issue.

I'd suggest trying the following:
- Restart the emulator
- Delete your Cache folder (in wow client)
- Make sure that the items you referenced actually exist
- Make sure that you put the right item / vendor ID's.

For more help relating to emulator issues you should go to OwnedCore.
If it doesn't show up in the database, it would be a TCreator issue, if that is the case, let me know here and i'll re-open the issue.
